[project]
name = "mmd-regime-detection"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "ipython>=9.8.0",
    "jupyter>=1.1.1",
    "matplotlib>=3.10.7",
    "seaborn>=0.13.2",
    "torch>=2.9.1",
    "yfinance>=0.2.66",
]
